### ISSUE TITLE
[1pt] Create empty My profile - Setup (group task)

### ISSUE THREAD

**Issue by TechnoAndy** [TechnoAndy/space-travelers-hub#3]
Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
This view should be empty - you will add content in separate tasks.

**Comment by AbayomiOlaoye** [comment]
I think we can safely close this, right?

**Comment by AbayomiOlaoye** [comment]
And the first two, maybe. @TechnoAndy , what do you think?

**Comment by TechnoAndy** [comment]
Yip, but don't delete the branch
